name: mostly_reasonable_lints
description: A mostly reasonable set of lints for Dart and Flutter projects.
repository: https://github.com/leanflutter/mostly_reasonable_lints
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  lints: ^3.0.0

topics:
  - lints
